framework:
    workflows:
        product:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Product
            initial_marking: prototyped
            places:
                - prototyped
                - implemented
                - tested
                - wrapped
                - shipped
            transitions:
                implement:
                    from: prototyped
                    to: implemented
                test:
                    from: implemented
                    to: tested
                wrap:
                    from: tested
                    to: wrapped
                ship:
                    from: wrapped
                    to: shipped



